Add README.md
AlexeyPerevalov/scheduler-plugins pull request #2
Opened 2021-01-19 19:44 UTC by swatisehgal

- Capture steps to configure and run topology-aware scheduler plugin

Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

2021-01-19 20:00 UTC, swatisehgal commented
/hold

2021-01-19 20:01 UTC, swatisehgal commented
This might need updates when we are able to get the latest version of the out of tree scheduler working. Currently the scheduler plugin is being debugged.

2021-01-22 00:26 UTC, swatisehgal commented
/hold cancel

2021-01-22 13:04 UTC, AlexeyPerevalov requested changes
Other than kubeconfig looks good for me)

2021-01-22 13:04 UTC, AlexeyPerevalov commented on pkg/noderesourcetopology/README.md
> +  # kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
I think we have to leave only one kubeconfig. I think it's better to keep
"/etc/kubernetes/scheduler.conf". I see it derives from examples.

2021-01-22 13:10 UTC, swatisehgal commented on pkg/noderesourcetopology/README.md
> +  # kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
Sure, will update

2021-01-22 13:14 UTC, swatisehgal commented on pkg/noderesourcetopology/README.md
> +  # kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
Done!

2021-01-22 13:24 UTC, AlexeyPerevalov approved these changes

2021-01-22 13:24 UTC, merged